discourse:
  host: "http://spicyfox.com"
  sso_url: "http://spicyfox.com/session/sso_provider"
  sso_secret: "98yfuf2h809239h8bgre"
  api_key: "5bd5aefe75d97fb96c5f0aed32964c9998f270b79fb5a3ad5e95a73eeecc9198"
  api_username: "spicyfox.admin"
