discourse:
  host:         "http://spicyfox.com"
  sso_url:      "http://spicyfox.com/session/sso_provider"
  sso_secret:   "98yfuf2h809239h8bgre"
  api_key:      "5bd5aefe75d97fb96c5f0aed32964c9998f270b79fb5a3ad5e95a73eeecc9198"
  api_username: "spicyfox.admin"
domain_mapping:
  "localhost":  "articles/studyaboard"
  "moonbbs.us": "articles/studyaboard"
sogou_scraper:
  search_query: "http://weixin.sogou.com/weixin?type=1&query="
  topic_creater:
    api_username: "crazyeditormiao"
    api_key: "285ff6c171ca40913730f1ed40e95800ebd41fb0fe8e408b9454afbad9ea5a95"
  gong_zong_hao: 
    "美国留学全方案": "studyaboard"
